### ISSUE TITLE
[ Request ] Various Issues and Improvement Suggestions

### ISSUE THREAD

**Issue by KrishnaPG** [dev-xo/remix-saas#257]
Thank you for providing this template. It is very helpful.

Encountering couple of problems and not sure how to address them. Any help is greatly appreciated.

 1.  I am able to run the project and login with eMail of admin. But in the billing section, the "manage" customer portal is failing (because user.customerId is NULL for admin).
 2. Tried with Github Auth, and was able to login, but after login it never goes to `dashboard` page. It is going back to `localhost:3000`. This is the same behavior on your live demo also. After social login it is taking to home-page rather than the dashboard. After debugging, it looks like below code is the culprit https://github.com/dev-xo/remix-saas/blob/a672e0587bce7f5196f64c4ee2e2990155e1b07c/app/routes/auth%2B/%24provider.callback.tsx#L11-L15
The redirect URLs are swapped. Making the `successRedirect` point to `DASHBOARD_PATH` resolved this problem.
 3. However, with Github emails there is another problem. The Github API does not automatically send email when it is declared as private. Hence the `profile._json.email` will be `null`. https://github.com/dev-xo/remix-saas/blob/a672e0587bce7f5196f64c4ee2e2990155e1b07c/app/modules/auth/auth.server.ts#L81-L94
 The email gets populated only in the `profile.emails` Hence changing the above code as below fixed that problem:
```js
      const email = profile._json.email || profile.emails[0].value;
      let user = await prisma.user.findUnique({
        where: { email },
        include: {
          image: { select: { id: true } },
          roles: { select: { name: true } },
        },
      })

      if (!user) {
        user = await prisma.user.create({
          data: {
            roles: { connect: [{ name: 'user' }] },
            email,
          },

```
  4. Could not find event handlers for Stripe customer deletion `customer.deleted` event. 
      I upgraded from `Stripe Stack` which had the event handlers for many Stripe events, which seem to be missing in this template. Would be great if the support for all events is added back into this.
  5. DB Seed code is currently creating the database entries directly for the plans, prices etc. https://github.com/dev-xo/remix-saas/blob/a672e0587bce7f5196f64c4ee2e2990155e1b07c/prisma/seed.ts#L101-L105
 Instead it should listen to the `plan.created` `price.created` etc. events from the Stripe webhook and create the equivalent entries in the database. This way the local database will always be kept in sync with the stripe. For example, when a price or plan is deleted it can be deleted or marked as inactive in the local database.

Thank you again for sharing this great work publicly. Some of these above changes can be make it much more refined.

**Comment by dev-xo** [comment]
Hello @KrishnaPG, you opened a huge issue, and I'm kinda busy lately. 

Not sure if you have time to open a PR with any fixes for some of the points exposed, but I would appreciate it.

> 1. Billing section, the "manage" customer portal is failing (because user.customerId is NULL for admin).
- Admin should probably not need to be able to subscribe or access the Customer Portal, that's only for users/customers. What would be your use case for admin being a customer too?

> 2. GitHub Auth login, but it never goes to the dashboard page.
- Yeah, that seems to be a typo here; swapping Login for Dashboard could do it. Good catch.

> 3. GitHub emails does not automatically send email when it is declared as private, hence `profile._json.email` will be null.
- Probably nothing we can do in that case. Not allowing the user to authenticate could keep us safe from empty or null emails. Any workarounds or thoughts on this you've got to handle this situation?

> 4. Could not find event handlers for Stripe customer deletion `customer.deleted event`.
- Isn't this being called anywhere? Interesting, will check. https://github.com/dev-xo/remix-saas/blob/a672e0587bce7f5196f64c4ee2e2990155e1b07c/app/routes/api%2B/webhook.ts#L129-L139

> DB Seed code is currently creating the database entries directly for the plans, prices, etc.
- The current workflow seems to work as expected, but probably implementing it like you exposed could be a better workaround.

As I said, I'm a bit busy lately, and not sure if I will be able to look into all these cases right now.
- Not sure if you could open any PR with a fix for any of the cases exposed, but I would appreciate that, and probably some of the folks who also use or will use the template will appreciate it too!

I will try to look into some of them myself too.

Thanks for the time invested in this issue, Krishna!

**Comment by KrishnaPG** [comment]
Thanks @dev-xo Created a pull-request for the code fixes https://github.com/dev-xo/remix-saas/pull/258  
  - social login redirection 
  - Github eMails

The remaining are Stripe event hooks that you can look into when you are free.

**Comment by dev-xo** [comment]
Merged, @KrishnaPG, thank you for that! Will try to find a moment to look into the Stripe thing, especially if it was implemented in Stripe Stack before! Any suggestions or insights that could speed up things will be welcomed!

**Comment by dev-xo** [comment]
Closing this for now, as customers usually should not be deleted but archived, in case there is any reportable issue for that customer to the payment provider itself, so probably it does not make much sense to delete that customer.

In case you or someone else is interested in how to do that, [here's](https://github.com/wanghaisheng/stripe-stack/blob/fcfa7432f7c89886cbab53311d023d4d63f58544/app/routes/resources%2B/user.delete.ts#L15-L36) a small example of it from a forker of the previous Remix SaaS template.
