### ISSUE TITLE
[ Question ] One-Time Payments with Stripe.

### ISSUE THREAD

**Issue by Hujjat** [dev-xo/remix-saas#276]
Hi there!

Firstly, thank you so much for the great work maintaining this important repo. 

I was wondering if there is support for one-time purchase. I setup the product in stripe as one time but not sure how that will be work this saas subscription planning. 

Please let me know if there is a doc that I missed about it. 

Thank you!

**Comment by dev-xo** [comment]
Hello @Hujjat.

Remix-SaaS is configured to handle only Subscriptions, although you probably can also handle one-time payments. In `stripe.checkout.sessions.create`, you will need to set the `mode` to `mode: 'payment'`.

Here's a gist I created some time ago for Remix. It showcases an example of one-time payments.
- https://gist.github.com/dev-xo/3f782eb4bf99fdc94e7b98a7337cccfa

I suggest checking the Stripe docs about one-time payments, as there is useful info that could help you!

**Comment by dev-xo** [comment]
Hello @Hujjat.

Remix-SaaS is configured to handle only Subscriptions, although you probably can also handle one-time payments. In `stripe.checkout.sessions.create`, you will need to set the `mode` to `mode: 'payment'`.

Here's a gist I created some time ago for Remix. It showcases an example of one-time payments.
- https://gist.github.com/dev-xo/3f782eb4bf99fdc94e7b98a7337cccfa

I suggest checking the Stripe docs about one-time payments, as there is useful info that could help you!

**Comment by Hujjat** [comment]
Thank you so much Daniel!
