### ISSUE TITLE
[ Question ] Set TOTP 64 Hex Characters

### ISSUE THREAD

**Issue by RyanDool** [dev-xo/remix-saas#288]
Running localhost and attempting to login via email, the following error occurs. 

Typed email and clicked "Continue With Email" a message appears "Secret must be a string with 64 hex characters." . When checking api logs I do not see any attempt to resend or to stripe. I also tried regenerating all new api keys, which did not resolve the issue. 

 
![Screenshot 2024-07-05 at 12 23 51 PM](https://github.com/dev-xo/remix-saas/assets/16748497/578a4020-4bb7-4e9d-b699-f64f765755a7)

**Comment by dev-xo** [comment]
Have you initialized the template with `npx create-remix-saas@latest`? If so, that TOTP string should be automatically set.

The `TOTP_SECRET` needs to be 64 hex characters as the error indicates, e.g.: "TOTP_SECRET=4570DE7251B98D442136595C4C129CB9932E2798F50F915CE8D09FB1239AD865"
- https://github.com/dev-xo/remix-auth-totp/tree/main/docs#1-implementing-the-strategy-instance
