### ISSUE TITLE
[ Issue ] ClientHintCheck - Warning: Prop `nonce` did not match.

### ISSUE THREAD

**Issue by Blaumaus** [dev-xo/remix-saas#318]
In `root.tsx` the `<ClientHintCheck nonce={nonce} />` seems to produce the following error:

<img width="952" alt="Screenshot 2024-09-08 at 02 18 35" src="https://github.com/user-attachments/assets/a2be8e24-90f1-4f7f-930c-184d2bb07e8f">

I'm running the app in Firefox.

**Comment by dev-xo** [comment]
Hello @Blaumaus, can you please check if you have the same issue in another browser, like Chrome or Brave? I do not have that issue myself.

Also:
- Has the template code been modified, or is it the base version (no changes)?
