### ISSUE TITLE
[ Auth ] Github OAuth issue Missing or invalid 'expires_in' field.

### ISSUE THREAD

**Issue by pvbhanuteja** [dev-xo/remix-saas#322]
Github oauth issue Missing or invalid 'expires_in' field

**Comment by dev-xo** [comment]
Will try to find a moment and check it @pvbhanuteja. Thanks for noticing!

**Comment by bp-armada** [comment]
@dev-xo firstly thanks for the nice work. 

This issue might be related to this : https://github.com/sergiodxa/remix-auth-github/issues/41

**Comment by pvbhanuteja** [comment]
Using github app instead of oauth fixes this but I dont think this should be go to solution but works for now.

**Comment by dev-xo** [comment]
Thanks guys. I'm a bit busy lately, so not sure the priority I can give to this fix, although I will try to find a moment to look into it.

If the solution is pretty clear, and you both have some free time, feel free to submit a PR and I will happily approve it. Again, thanks for noticing!

**Comment by pvbhanuteja** [comment]
@dev-xo https://github.com/dev-xo/remix-saas/pull/323

**Comment by dev-xo** [comment]
Adding the provided info into a new commit @pvbhanuteja! Thanks for letting us the Github Issue and how to fix it!
