### ISSUE TITLE
[ Docs ] Include instructions about seeding the db and first login.

### ISSUE THREAD

**Issue by ceaucari** [dev-xo/remix-saas#328]
Thanks for the great work Daniel!

I noticed after the first installation process it's unclear why login doesn't work without having seeded the db first. 
[This PR](https://github.com/dev-xo/remix-saas/pull/327) adds instructions to the README about that.

This issue [ #233 ](https://github.com/dev-xo/remix-saas/issues/233) is also related.

**Comment by dev-xo** [comment]
Thanks @ceaucari, replied on #223!
