### ISSUE TITLE
[ Docs ]: Improve Social Login Instructions

### ISSUE THREAD

**Issue by airtonix** [dev-xo/remix-saas#341]
@dev-xo in [this commit](https://github.com/dev-xo/remix-saas/commit/2e512f5a4acfe28fea9705c6534990d53eb7faa6) you point to [changed files in this pr here](https://github.com/dev-xo/remix-saas/pull/323/files) with a comment that 

> Here's a Pull Request that also includes 2 images to guide you through the process

However: 

1. the link does not directly reveal the mentioned images
2. once i found the initial commit for the PR, [the 2 images](https://github.com/dev-xo/remix-saas/pull/323/commits/d75c6e7f040ca839ffe15abf7f1a3c2b8f56e354) only indicate partial steps of a much larger set of steps.

To make this documentation more complete and less of a reminder to those who 

> Already Know Things ™️ 

We should list all the steps required to successfully create a Github App that successfully works with remix-sass.

Obvious things missing: 

- what should we put in the callback url? 
- guidance that the user should create a separate Github App per deployment environment: 
  - `[LOCAL] Your AppName` for local development
  - `[DEV] Your Appname` for qa environment
  - `Your Appname` for prod environment

**Comment by dev-xo** [comment]
Hello @airtonix,

First of all, thank you for the PR https://github.com/dev-xo/remix-saas/pull/342

Secondly, there are probably better ways to communicate or ask for help, while keeping the mad tone or the funny jokes like "Already Know Things™️" away.

I'm currently a bit busy, not being fully able to dedicate that much time to Remix SaaS. I probably rushed a few commits, mislabeling some names and probably not adding that much value to the documentation when I looked into the Github OAuth topic.

With that said, Remix Saas also states that this is not a fully-fledged app, and you may need to know the technologies being used. We do not aim to provide a step-by-step introduction to any of the modules or blocks, as it is the case with social auth. You may need to consult the appropriate docs (such as OAuth ones) for some solutions.

Again, thanks for the PR. It will be reviewed and probably merged, especially if it clarifies things for others on social logins, as there was another case on this topic before.

As a small suggestion, don’t be angry at a free resource someone is offering to you. We do not aim for perfection here, and people are not always able to keep things as updated as you might like those to be.

Thanks.
