### ISSUE TITLE
[ Question ] Issue with Fly.io deployment.

### ISSUE THREAD

**Issue by zrachlin** [dev-xo/remix-saas#343]
Hey there - thanks for this template.

I just followed the instructions for getting the repo set up, and then went through the deployment instructions. Everything went smoothly until the end, when I got the following message:
```
WARNING The app is not listening on the expected address and will not be reachable by fly-proxy. Machine {machine} [app] update finished: success
You can fix this by configuring your app to listen on the following addresses:
  - 0.0.0.0:3000
Found these processes inside the machine with open listening sockets:
  PROCESS        | ADDRESSES                         
-----------------*-----------------------------------
  /.fly/hallpass | [fdaa:a:ff25:a7b:8:c7:5033:2]:22  
```

Any idea why this is happening or how to fix it?

**Comment by dev-xo** [comment]
Hello @zrachlin,

I’ve seen those Fly errors before, and to be honest, I’m not sure if they’re related to the template or the service itself. In the past, I fixed them by re-deploying and ensuring the ENVs was properly set, also check `Dockerfile` as I think it was related to it too .

I suggest checking if all the ENVs are set correctly, checking `Dockerfile` ports, deleting the Fly App, and trying to deploy again.

- - -

Also, please, have a search on Google for the error. If I recall correctly, there were similar cases, and someone might have posted specific solutions or some hints.

With that said, please let me know if you find anything else, as I can't say much more at the moment!

**Comment by MichaelDeBoey** [comment]
CC/ @rubys

**Comment by dev-xo** [comment]
Closing for now, no response from OP.

**Comment by rubys** [comment]
There are two common causes for this:
  * Startup takes longer than the default grace period, but the application does eventually start.  In which case, the message can be ignored.  The message can be made to go away by adjusting the grace period.  https://fly.io/docs/reference/configuration/#http_service-checks
  * Service never starts, due to an error.  Check the logs for more information.  https://fly.io/docs/monitoring/logging-overview/

**Comment by dev-xo** [comment]
Thanks for the clarification, @rubys!
