### ISSUE TITLE
confusion between sessionUser and User.

### ISSUE THREAD

**Issue by lhapaipai** [dev-xo/remix-saas#349]
Hello and thank you very much for this super accomplished stack !

I'm a bit confused about user object stored in session for authentication.

```ts
// app/modules/auth/auth.server.ts

import type { User } from '@prisma/client'
/**
type User = {
    id: string;
    createdAt: Date | null;
    updatedAt: Date | null;
    email: string;
    username: string | null;
    customerId: string | null;
}
*/
export const authenticator = new Authenticator<User>(authSessionStorage)
```

but in fact our strategies return  a more complete user

```ts
let user: {
    roles: {
        name: string;
    }[];
    image: {
        id: string;
    } | null;
} & {
    id: string;
    createdAt: Date | null;
    updatedAt: Date | null;
    email: string;
    username: string | null;
    customerId: string | null;
}
```

so I wonder if the distinctions `requireSessionUser`, `requireUser` are useful because they can bring confusion. and need to be perfectly synchronized.

for example following a first TOTP connection a user is created in session, he doesn't have username and customerId.
```json
{
  "user": {
    "id": "cm3g6iqp80000yviqelw9kpil",
    "email": "admin1@admin.com",
    "username": null,
    "customerId": null,
    "createdAt": "2024-11-13T17:52:48.044Z",
    "updatedAt": "2024-11-13T17:52:48.044Z",
    "image": null,
    "roles": [
      {
        "name": "user"
      }
    ]
  }
}
```
the user is redirected to the onboarding page and is prompted to enter a username.

after that user is updated in database.
```json
{
  "user": {
    "id": "cm3g6iqp80000yviqelw9kpil",
    "email": "admin1@admin.com",
    "username": "admin1",
    "customerId": "cus_RDB6YRIZlaar1e",
    "createdAt": "2024-11-13T17:52:48.044Z",
    "updatedAt": "2024-11-13T17:52:52.753Z",
    "image": null,
    "roles": [
      {
        "name": "user"
      }
    ]
  }
}
```
but user in session remain out of sync with
```json
{
  "user": {
    "id": "cm3g6iqp80000yviqelw9kpil",
    "email": "admin1@admin.com",
    "username": null,
    "customerId": null,
    "createdAt": "2024-11-13T17:52:48.044Z",
    "updatedAt": "2024-11-13T17:52:48.044Z",
    "image": null,
    "roles": [
      {
        "name": "user"
      }
    ]
  }
}
```

what do you think about it?
looking forward to reading you !

**Comment by dev-xo** [comment]
Hello again @lhapaipai.

As mentioned before, some of the code is from a previous Stack, and although everything works as expected, a few situations could be managed differently or in a better way.

I can't say much more right now, as it's been some time since I properly looked into the code, but as far as I remember, the user model will be updated after Onboarding, so some properties may not be there yet, as you showed in the authentication file.

Again, I plan to update the stack (improving it with the release of Remix v3), so for now, feel free to apply patches or even open a PR for the issue you mentioned (out-of-sync properties for User in session).

**Comment by lhapaipai** [comment]
as you said, everything works as expected, if you plan to update the stack with the arrival of Remix v3. I will wait for that to discuss it again and apply a PR.

thanks again

**Comment by dev-xo** [comment]
Yep! In any case, if you find some areas we could improve or update before the release of Remix v3 and the stack rebuild, feel free to open an issue or even submit a PR!

Again, thanks for the care and the great messages, @lhapaipai!
