### ISSUE TITLE
[ Auth ] crypto is not defined

### ISSUE THREAD

**Issue by fabricioloupias** [dev-xo/remix-saas#358]
I'm having a problem, I imagine it may happen to others too...

I want to log in as administrator (admin@admin.com) in development mode and I get an error message "crypto is not defined"

![image](https://github.com/user-attachments/assets/82f2584f-e0e1-4cda-8ffc-e0612f80fbc3)

**Comment by dev-xo** [comment]
Hello @fabricioloupias, haven't seen that before. Can you please give more details?

- What's the version of `remix-auth` and `remix-auth-totp` you are using?
- Is the implementation based on Cloudflare?

Any detail you may be able to give could help with this, as I haven't seen that issue before.

**Comment by fabricioloupias** [comment]
> Hello @fabricioloupias, haven't seen that before. Can you please give more details?
> 
> * What's the version of `remix-auth` and `remix-auth-totp` you are using?
> * Is the implementation based on Cloudflare?
> 
> Any detail you may be able to give could help with this, as I haven't seen that issue before.

I followed the steps in the documentation (https://github.com/dev-xo/remix-saas/tree/main/docs#remix-saas-documentation) only. I haven't been able to deploy it yet. I don't see any other errors in the console (both in inspector and stdout)

- `npx create-remix-saas@latest`
- set environment variables
- `npm run dev`

These are the dependencies that were installed:

    "@conform-to/react": "1.2.2",
    "@conform-to/zod": "1.2.2",
    "@epic-web/client-hints": "^1.3.5",
    "@prisma/client": "5.20.0",
    "@radix-ui/react-dropdown-menu": "^2.1.2",
    "@radix-ui/react-select": "^2.1.2",
    "@radix-ui/react-slot": "^1.1.0",
    "@radix-ui/react-switch": "^1.1.1",
    "@react-email/components": "^0.0.25",
    "@react-email/render": "^0.0.17",
    "@remix-run/express": "^2.14.0",
    "@remix-run/node": "^2.13.1",
    "@remix-run/react": "^2.14.0",
    "@remix-run/router": "^1.20.0",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "compression": "^1.7.4",
    "cookie": "^1.0.1",
    "cross-env": "^7.0.3",
    "express": "^4.21.1",
    "express-rate-limit": "^7.4.1",
    "helmet": "^7.2.0",
    "i18next": "^23.16.5",
    "i18next-browser-languagedetector": "^8.0.0",
    "isbot": "^4.1.0",
    "lucide-react": "^0.460.0",
    "morgan": "^1.10.0",
    "prisma": "^5.21.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-email": "^2.1.6",
    "react-i18next": "^15.0.3",
    "remix-auth": "^3.7.0",
    "remix-auth-github": "^2.0.0",
    "remix-auth-totp": "^3.4.2",
    "remix-i18next": "^6.4.1",
    "remix-utils": "7.0.0-pre.4",
    "sonner": "^1.5.0",
    "stripe": "^16.12.0",
    "tailwind-merge": "^2.5.4",
    "tailwindcss-animate": "^1.0.7",
    "tsx": "4.19.0",
    "zod": "^3.23.8"

**Comment by dev-xo** [comment]
No idea, to be honest, @fabricioloupias.

I will need to give it a try too, as probably one of the latest dependency updates may have broken the auth somehow. I'm a bit busy currently and not sure when I will be able to look into it, especially with a new Remix SaaS on the way, but I will try to find some time to look into it and replicate your install.

Feel free to share any other details you may find during debugging or anything else.  
Thanks!

**Comment by ttpss930141011** [comment]
I also had a similar issue long time ago, and I fixed it with upgrading my Node.js to the latest version.
I didn't research deeper but I guess it's an error from Web Cryptography API...
